### ISSUE TITLE
Local mode 

### ISSUE THREAD

**Issue by MichaelMMeskhi** [BYU-PRISM/GEKKO#110]
Hello, 

Using `m=model(remote=False)` runs the APOPT solver on my local CPU as I understand. I get an error that no path was found to `results.json`. How to fix this?

**Comment by APMonitor** [comment]
You may get this error if no solution is found. Please try this code:

```python
from gekko import GEKKO
m = GEKKO(remote=False)            # create GEKKO model
x = m.Var()            # define new variable, default=0
y = m.Var()            # define new variable, default=0
m.Equations([3*x+2*y==1, x+2*y==0])  # equations
m.solve(disp=False)    # solve
print(x.value,y.value) # print solution
```

If there is still a problem with the above code then please let me know what is the Operating System (OS) and other machine specifications.

**Comment by MichaelMMeskhi** [comment]
I usually use remote True and been solving the same objective but recently need local. Why would local solver not find a solution? Is this possible? I’ll test that out now.

**Comment by MichaelMMeskhi** [comment]
> You may get this error if no solution is found. Please try this code:
> 
> ```python
> from gekko import GEKKO
> m = GEKKO(remote=False)            # create GEKKO model
> x = m.Var()            # define new variable, default=0
> y = m.Var()            # define new variable, default=0
> m.Equations([3*x+2*y==1, x+2*y==0])  # equations
> m.solve(disp=False)    # solve
> print(x.value,y.value) # print solution
> ```
> 
> If there is still a problem with the above code then please let me know what is the Operating System (OS) and other machine specifications.

The code works fine. The program I have is later compiled using `pyinstaller` into an exec. Would that be an issue?

**Comment by APMonitor** [comment]
Here is some help with `pyinstaller` and `gekko`: https://stackoverflow.com/questions/66181211/compiling-gekko-with-pyinstaller  You need to let `pyinstaller` know about the local run directory `m.path`.
