### ISSUE TITLE
Problem with Linear Programming example

### ISSUE THREAD

**Issue by larsRikard** [BYU-PRISM/GEKKO#129]
I'm running gekko 1.0.1 with python 3.9.7
I tried running the example code from the example files:
https://github.com/BYU-PRISM/GEKKO/blob/master/examples/linear_program.py

But it doesn't solve or crash after 5 minutes. Is this a known issue?
Also I couldn't find where to choose the solver, what linear solvers does gekko use?

**Comment by larsRikard** [comment]
nvm, it works with:
m = GEKKO(remote = False)
Though I don't know what it does or why it is needed

**Comment by APMonitor** [comment]
`remote=False` solves locally without an internet connection. If there is a problem with the public server or the connection to the server then there is an error message that the server is not available.

**Comment by APMonitor** [comment]
Here is a description of the solver options: https://apmonitor.com/wiki/index.php/Main/OptionApmSolver
