### ISSUE TITLE
ini equations problem?

### ISSUE THREAD

**Issue by aliule2020** [BYU-PRISM/GEKKO#135]
if I want use V1_0 represent the ini value of V1,V2_0 represent the ini value of V2,and has the equation V2_0-V1_0=5,how should I do?

**Comment by APMonitor** [comment]
Great question! Please post the question to StackOverflow with tag [gekko]. We use GitHub to track bugs or features requests, not support questions. Here is the list of questions and answers on StackOverflow with tag gekko: https://stackoverflow.com/questions/tagged/gekko
