### ISSUE TITLE
Changing run directory does not work

### ISSUE THREAD

**Issue by moowees** [BYU-PRISM/GEKKO#136]
Changing the run rundirectory with: 
m.path='...' does not work. 
The files are still created in the temp folder

> from gekko import GEKKO
> import numpy as np
> import os

> rd=r'.\RunDir'
> if not os.path.isdir(os.path.abspath(rd)):
>     os.mkdir(os.path.abspath(rd))
> m = GEKKO(remote=False)         # solve locally
> m.path = os.path.abspath(rd)   # change run directory
> x = m.Array(m.Var,4,value=1,lb=1,ub=5)
> x1,x2,x3,x4 = x                 # rename variables
> x2.value = 5; x3.value = 5      # change guess
> m.Equation(np.prod(x)>=25)      # prod>=25
> m.Equation(m.sum([xi**2 for xi in x])==40) # sum=40
> m.Minimize(x1*x4*(x1+x2+x3)+x3) # objective
> m.solve(disp=False)
> print(x)

**Comment by APMonitor** [comment]
Does this help? https://stackoverflow.com/questions/56916393/specify-output-directory-of-solution-file-in-python-gekko-or-matlab-apm/  Try using `m._path` instead. This is a great question. If you still need additional help, please consider creating a StackOverflow question with tag [gekko].
