### ISSUE TITLE
Error using  "m.asinh" 

### ISSUE THREAD

**Issue by Flomel0109** [BYU-PRISM/GEKKO#140]
Hello,

When I use the m.asinh function ("inverse hyperbolic sine, sinh^-1(x)" in the gekko documentation), 

EXAMPLE : 

"""
m.Equations([g.dt()==m.asinh(r), J==d-g])

"""

I get this error message: 

"""

Exception: @error: Template expression
 *** Error in the syntax of the function string : Missing opening parenthesis

Position: 10                  
$v1-(asinh(p2))
               ?

"""

I'm pretty sure the parentheses are correctly placed because replacing "asinh" with another similar function like "atan" works without any problems. Could it be a problem with the implementation of the "asinh" function in the Gekko space?

Kind regards,

FLOMEL0109

**Comment by APMonitor** [comment]
Thanks for highlighting this bug. I've assigned it to be fixed for the next gekko release.

**Comment by APMonitor** [comment]
Fixed in Gekko v1.0.3
