### ISSUE TITLE
Better error when no solution found

### ISSUE THREAD

**Issue by marcosfelt** [BYU-PRISM/GEKKO#150]
Currently, when the solver doesn't find a solution, it raises a generic exception. Using a generic exception makes it difficult to specifically catch failed solutions and do custom error handling.

https://github.com/BYU-PRISM/GEKKO/blob/3e2698a5324a5fce87a659c94ae3c7cd1bff7922/gekko/gekko.py#L2140

Would you accept a PR that creates a custom error for failed solutions?

**Comment by APMonitor** [comment]
Try setting `debug=0` to allow the code to proceed without the exception with `m.solve(debug=0)`. The status is reported by [m.options.APPSTATUS](https://apmonitor.com/wiki/index.php/Main/OptionApmAppstatus) or [m.options.APPINFO](https://apmonitor.com/wiki/index.php/Main/OptionApmAppinfo) for more specific error information.
