### ISSUE TITLE
Could not find the optimal solution after adding constraints.

### ISSUE THREAD

**Issue by LiuXiaoxuanPKU** [BYU-PRISM/GEKKO#158]
Hi, thanks for the great library! However, I met the problem of not finding the optimal solution after adding constraints.

My code is as follows:
```
gekko = GEKKO(remote=True)
# create variable, each variable is a vector, each element of the vector is a binary
s = []
for i in range(N):
    s.append(gekko.Array(gekko.Var, data.s_len[i], value=0, lb=0, ub=1, integer=True))
# some constants used in the objective/constraint function
c, d, r, m, L = create_c_d_r_m_L() # they are all numpy ndarry
 
# define the objective function
def objective():
    obj = 0
    for i in range(N):
        obj += np.dot(s[i], c[i]) + np.dot(s[i], d[i])
    for idx, (i, j) in enumerate(E):
        obj += np.dot(np.dot(s[i], r[idx].reshape(s_len[i], s_len[j])), s[j]) # s[i] * r[i, j] * s[j]
    return obj

# add constraints
# (a) each vector can only have and must have one 1
for i in range(N):
    gekko.Equation(gekko.sum(s[i]) == 1)
# (b) 
for t in range(N):
    peak_mem = gekko.sum([np.dot(s[i], m[i]) for i in L[t]])
    gekko.Equation(peak_mem < DEVICE_MEM) # DEVICE_MEM is a predefined big int
```

I found that when removing constraint (b), the solver can output the optimal solution for s. However, if we add (b) and set DEVICE_MEM to a very large number (which should not affect the solution), the s is not optimal anymore. I'm wondering if I am doing something wrong here because I tried both APOPT(solvertype=1) and IPOPT (solvertype=3) and they give the same nonoptimal results.

I've been stuck on this for a while and any comments/answers are highly appreciated! Thanks!

**Comment by APMonitor** [comment]
Could you post this application question to StackOverflow with tag [gekko]? https://stackoverflow.com/questions/tagged/gekko

**Comment by APMonitor** [comment]
Please include an example `data` DataFrame and `create_c_d_r_m_L()` in your StackOverflow question so that we can reproduce the problem and provide more specific suggestions.

**Comment by LiuXiaoxuanPKU** [comment]
yes, posted and added, please take a look, thanks a lot!

Question link:
https://stackoverflow.com/questions/75377533/could-not-find-the-optimal-solution-after-adding-constraints

**Comment by LiuXiaoxuanPKU** [comment]
I can also send my code directly if that's more helpful. But the code contains some customized code, it's better to send it to gekko people instead of posting it publicly.
