### ISSUE TITLE
Gekko_GPR error

### ISSUE THREAD

**Issue by Luisenden** [BYU-PRISM/GEKKO#165]
Hi, I want to use the gekko.ML lib to optimize a built Sklearn GaussianProcessRegressor. I therefore extended the example given in the [docs](https://gekko.readthedocs.io/en/latest/ml.html?highlight=predict) from one feature x to two features x1,x2.
Here I encounter the error: `ValueError: operands could not be broadcast together with shapes (2,) (0,) ` for the Gekko_GPR model - interestingly however, when I use Gekko_SVR with the very same example, everything works smoothly. Here comes the code (I ran it in a Jupyter notebook, if that makes any difference)

```python
#Import the ML interface functions
from gekko.ML import Gekko_GPR,Gekko_SVR,Gekko_NN_SKlearn
from gekko.ML import Gekko_NN_TF,Gekko_LinearRegression
from gekko.ML import Bootstrap,Conformist,CustomMinMaxGekkoScaler
import pandas as pd
from sklearn.model_selection import train_test_split


#Source function to generate data
def f(x):
    return np.cos(2*np.pi*x)

#represent noise from a data sample
N = 350
x1 = np.linspace(0,1.2,N)
x2 = np.linspace(0,1.2,N)
noise = np.random.normal(0,.3,N)
y_measured = f(x1) + noise + x2

#Training the Data and split it
data = pd.DataFrame(np.array([x1,x2,y_measured]).T,columns=['x1','x2','y'])
features = ['x1', 'x2']
label = ['y']

train,test = train_test_split(data,test_size=0.2,shuffle=True)

#Training the models
import sklearn.gaussian_process as gp
from sklearn.neural_network import MLPRegressor
from sklearn import svm
from sklearn.metrics import r2_score

#SVR
svr = SVR()
svr.fit(train[features],train[label])

#SVR Optimization
from gekko import GEKKO
m = GEKKO()
x1 = m.Var(0,lb=0,ub=1)
x2 = m.Var(0,lb=0,ub=1)
y = Gekko_SVR(svr,m).predict([x1,x2]) #function is used here
m.Obj(y)
m.solve(disp=False)
print('solution SVR:',y.value[0])
print('x:',x1.VALUE, x2.VALUE)
print('Gekko Solvetime:',m.options.SOLVETIME,'s')
m.cleanup()


#GPR
k = gp.kernels.RBF() * gp.kernels.ConstantKernel() + gp.kernels.WhiteKernel()
gpr = gp.GaussianProcessRegressor(kernel=k,\
                            n_restarts_optimizer=10,\
                            alpha=0.1,\
                            normalize_y=True)
gpr.fit(train[features],train[label])

#GPR Optimization
m = GEKKO()
x1 = m.Var(0,lb=0,ub=1)
x2 = m.Var(0,lb=0,ub=1)
y = Gekko_GPR(gpr,m).predict([x1,x2]) #function is used here
m.Obj(y)
m.solve(disp=False)
print('solution GPR:',y.value[0])
print('x:',x1.VALUE, x2.VALUE)
print('Gekko Solvetime:',m.options.SOLVETIME,'s')
m.cleanup()
```

**Comment by llgunnell7** [comment]
Hi Luisenden, 

I am unable to replicate the problem with the provided code. After adding an import line for numpy/svr, I get the following output:

``solution SVR: -0.47303126492
x: [0.48473545497] [0.48473545497]
Gekko Solvetime: 0.01999999999 s
solution GPR: -0.49248511311
x: [0.47242321739] [0.47242321739]
Gekko Solvetime: 0.029999999999 s``

The problem may be because of how you are formatting the problem if you are using a different data source, or possibly a library that is not updated. I suggest updating python and all relevant packages. If you still have trouble, please share additional error messages or python environment details.

**Comment by Luisenden** [comment]
Many thanks IIgunnell7, that solved it - the numpy version I used was not up-to-date.

**Comment by APMonitor** [comment]
Issue resolved. Thanks to @llgunnell7 and @Luisenden for the discussion and feedback.
