### ISSUE TITLE
Error in the docs

### ISSUE THREAD

**Issue by PerplexedFox** [BYU-PRISM/GEKKO#166]
I think there is a small error in the [documentation #Diagnostics](https://gekko.readthedocs.io/en/latest/quick_start.html#diagnostics) git:  [here](https://github.com/BYU-PRISM/GEKKO/blob/master/docs/quick_start.rst#diagnostics)
shouldn't it be **m._path** instead of **m.path**? 
m.path doesn't work, whereas m._path executes as intended.

**Comment by APMonitor** [comment]
Thanks for that correction. `m._path` is correct and `m.path` is an alias that also works, but just to display the default path. Use `m._path` if you need to change the local directory path. I've updated the documentation.
