### ISSUE TITLE
Automatic Variable Naming

### ISSUE THREAD

**Issue by nsgates** [BYU-PRISM/GEKKO#17]
It would be useful to have variables be named automatically to whatever they are set equal to, instead of requiring separate names designated inside of quotes.

**Comment by loganbeal** [comment]
@nsgates I agree that this would be a great feature. I have not found a way to do this in python. 
Can you generate a working example of returning the variable name from the python namespace during a variable assignment?

**Comment by loganbeal** [comment]
@nsgates Have you discovered any way to accomplish this? My searches have all indicated that this is not possible.
