### ISSUE TITLE
Increase in RAM usage while optimisations are running

### ISSUE THREAD

**Issue by gabdab1012** [BYU-PRISM/GEKKO#170]
I've been running the same optimization multiple times consecutively and observed that the RAM usage consistently increases. This poses a problem because, after a certain period, the RAM becomes fully utilized, causing the PC to crash.

Do you have any suggestions on how to address this issue?

Best regards,

**Comment by APMonitor** [comment]
Gekko runs as a sub-process and releases the memory after every `m.solve()` completes. There is something in your Python script that is retaining memory. This can be cleared with `gc` a Python [Garbage Collector interface](https://docs.python.org/3/library/gc.html). The hard drive memory can also be cleared by deleting the temporary run directory with `m.cleanup()`. The hard drive space is unrelated to the RAM usage. Here is an example of using both `gc` and `m.cleanup()`.

```python
import gc
import copy
from gekko import GEKKO

# Number of iterations
num_iterations = 5

# Create a list to store the Gekko models
models = []

# Create and solve Gekko models in a loop
for i in range(num_iterations):
    m = GEKKO(remote=False)

    # Define variables, equations, and objectives for your optimization problem
    m.x = m.Var(value=0.5, lb=0, ub=3)
    m.y = m.Var(value=0.5, lb=0, ub=2)
    m.Minimize((m.x-i)**2 + (m.y-i)**2)

    # Solve the optimization problem
    m.options.SOLVER=1
    m.solve(disp=False)
    
    # Append the model to the list
    models.append(m)

    # Clean up resources after each solve
    m.cleanup()   # delete temporary directory (release hard drive space)
    del m         # delete m object (release RAM use)
    gc.collect()  # garbage collection

# Now you can access the solutions from each iteration
for i, model in enumerate(models):
    print(f"Iteration {i + 1}:")
    print(f"x = {model.x.value[0]}")
    print(f"y = {model.y.value[0]}")
    print(f"Objective = {model.options.OBJFCNVAL}\n")

# Clean up the list of models and release resources
models.clear()
gc.collect()
```
