### ISSUE TITLE
Spontaneous Access Violation errors when remote is set to false

### ISSUE THREAD

**Issue by PerplexedFox** [BYU-PRISM/GEKKO#171]
I described the error in the following stackoverflow [question](https://stackoverflow.com/questions/77172868/gekko-connection-variable-a-not-found). The interesting part is that as soon as I returned to the previously working code (with constant pressure and other variables determined from coolprop with bsplines) suddenly the error appeared and would not go away. 

> Error: Exception: Access Violation
> At line 3157 of file custom.f90
> Traceback: not available, compile with -ftrace=frame or -ftrace=full
> 
> Error: 'results.json' not found. Check above for additional error details
> 
> FileNotFoundError: [Errno 2] No such file or directory: '...\\options.json'

If solved with `Remote=True` the error does not appear at all!
**Update**: since today the remote solution results in 

> HTTPError: HTTP Error 404: Not Found
> During handling of the above exception, another exception occurred:
> ImportError: No solution or server unreachable.
>   Show errors with m.solve(disp=True).
>   Try local solve with m=GEKKO(remote=False).

It does seem like the [issue](https://stackoverflow.com/questions/67431986/gekko-minlp-error-options-json-file-not-found) 2 years ago, where the solver crashed...

**Comment by APMonitor** [comment]
New issue created to track this bug and the resolution. https://github.com/BYU-PRISM/GEKKO/issues/173
