### ISSUE TITLE
Error in IMODE 3 when variables are not initialized to values

### ISSUE THREAD

**Issue by abe-mart** [BYU-PRISM/GEKKO#18]
Optimizing in IMODE 3 gives a CSV_READ error when variables are initialized without values.

**Comment by abe-mart** [comment]
Example:
```
from gekko import GEKKO
m = GEKKO()
x = m.Var()
m.Obj(x**2)
m.options.IMODE = 3
m.solve()
```
Gives the error 
`Error: include CSV data in 10.8.33.233_gk_model0.csv when CSV_read is ON
 STOPPING. . .`

**Comment by loganbeal** [comment]
@abe-mart Nice find. @APMonitor is going to fix this in the back-end to be a warning rather than a fatal error.

**Comment by loganbeal** [comment]
@abe-mart The latest GEKKO packages include an updated executable that corrects this error. The executables on the remote servers will be updated shortly.

**Comment by APMonitor** [comment]
The executable on the public servers byu.apmonitor.com and xps.apmonitor.com are updated.
