### ISSUE TITLE
Gekko_GPR error with multi features problem

### ISSUE THREAD

**Issue by sangnguyens** [BYU-PRISM/GEKKO#182]
it seems Gekko_GPR does not support for multi features problem.
It rased error:
` ValueError: operands could not be broadcast together with shapes (7,) (0,) `

**Comment by APMonitor** [comment]
It looks like it could be a problem with the output label data. Could you create a simple and complete version of your problem that reproduces the error and post it to StackOverflow with tag "gekko"? https://stackoverflow.com/questions/tagged/gekko

**Comment by APMonitor** [comment]
I found an issue in the `ML.py` code that may fix the problem. Could you try `v1.1.1` when it is released?

**Comment by sangnguyens** [comment]
I'll give a try today

**Comment by APMonitor** [comment]
This may also help. https://stackoverflow.com/questions/78369831/i-want-to-minimize-predicted-pel-obtained-from-neural-network-by-using-2-decisio Please re-open the issue if you can post a minimal and complete example of the problem.
