### ISSUE TITLE
Unable to specify multiple solver options

### ISSUE THREAD

**Issue by kmg-dev** [BYU-PRISM/GEKKO#186]
Hi,

When I try to specify multiple options for Ipopt, I get the error `Error reading value for tag mu_strategy from file.`
**This is independent of any specific options or the order in which options are specified**. It occurs as soon as there is more than one option.

Example to reproduce with Gekko v1.2.1:
```Python
import numpy as np
from gekko import GEKKO

m = GEKKO(remote=False)
m.time = np.linspace(0, 20, 100)
k = 10
y = m.Var(value=5.0)
t = m.Param(value=m.time)
m.Equation(k * y.dt() == -t * y)
m.options.IMODE = 4
m.solver_options = ["linear_solver ma27", "mu_strategy adaptive"]
m.solve(disp=True)
```

I'd be happy to contribute in fixing this issue if you are accepting external contributions.

**Comment by kmg-dev** [comment]
Further update to this. It seems that only the last option is ignored. Adding an empty string seems to resolve it, like below:
```Python
m.solver_options = ["linear_solver ma27", "mu_strategy adaptive", ""]
```

Would be nice not to have to do this so leaving it open as a potential bug.

**Comment by APMonitor** [comment]
Thanks for finding this issue with local solve mode. It has been fixed with this commit: https://github.com/BYU-PRISM/GEKKO/commit/b6ea07389d2e19e534d429e80ff4376c41e963c9 that will be released with the next version of Gekko.
