### ISSUE TITLE
Public Server Status?

### ISSUE THREAD

**Issue by knavely** [BYU-PRISM/GEKKO#187]
Is the gekko public server down temporarily?

I am running IPOPT with remote=True, and it was all working yesterday, but all day today it stalls out and then throws a 

> Model file does not exist: 73.231.228.230_gk_model0.apm
 STOPPING...

Unfortunately I can not figure out how to run IPOPT locally, so remote = False isnt really an option right now. Thanks in advance for any clarification here.

**Comment by APMonitor** [comment]
With 200k+ downloads per month, the servers are sometimes overloaded with long or big jobs. If you need IPOPT locally, the Windows version of Gekko includes IPOPT as a local option. The public servers should also be available again.

**Comment by knavely** [comment]
many thanks you for the helpful info! So if I grab windows and do a pip install gekko on it, that will include IPOPT local?

**Comment by APMonitor** [comment]
Yes, that is correct. It uses a version of IPOPT with a linear solver that can be distributed publicly. The performance may be slightly less than the version on the public server. More information on the local executables is here: https://github.com/BYU-PRISM/GEKKO/tree/master/gekko/bin
