### ISSUE TITLE
result using coolprop seems to be wrong

### ISSUE THREAD

**Issue by fatsen** [BYU-PRISM/GEKKO#188]
When calculating with coolprop, the result seems to be wrong. The scripts below is simplified to show the problem.
```python
from CoolProp.CoolProp import PropsSI   #coolprop's source code is C++, and it has a python wrapper.
from gekko import GEKKO

m = GEKKO(remote=False)

a = m.Var(value=1, name='a')
t = m.Var(value=20, name='t')

fluid_name = 'Water'
# m.Equation(a + PropsSI('P', 'Q', 1, 'T', t + 273.15, fluid_name) / 1000 == 0) 
# with the above equation, [TypeError: must be real number, not GK_Operators] will be raised.
m.Equation(a + PropsSI('P', 'Q', 1, 'T', t.value + 273.15, fluid_name) / 1000 == 0)
m.Equation(a + t == 0)
m.solve()

for i in m._variables:
    print(i.name, i.value)

print(a.value[0] + PropsSI('P', 'Q', 1, 'T', t.value[0] + 273.15, fluid_name) / 1000)  # should be zero
print(a.value[0]+t.value[0])  # should be zero
```

the outputs are:
```
a [-2.3393181883]
t [2.3393181883]
-1.6160227470100634
0.0
```

The output of [-1.616] should be 0. Other equations not using coolprop are OK.
Is coolprop not compatible with gekko?
Thank you very much.

**Comment by APMonitor** [comment]
This is a great question, but it would be better to post on StackOverflow. See a related question on `CoolProp` and `gekko`: https://stackoverflow.com/questions/62832981/gekko-and-coolprop

The issue you're encountering is that `GEKKO` cannot directly handle calls to external libraries like `CoolProp` within the equation-building process. `GEKKO` expects explicit mathematical expressions that it can compile with automatic differentiation for optimization, but `CoolProp`'s `PropsSI` function doesn't provide this.

To fix this, you can decouple `CoolProp` calculations from the `GEKKO` equations by calculating the thermodynamic properties outside of the `GEKKO` model (before defining the equations). One workaround is to update the variables dynamically after solving the model or use a cubic spline, as demonstrated below. Here’s how you can modify your script to avoid direct `CoolProp` calls in `GEKKO`'s equations:

```python
from CoolProp.CoolProp import PropsSI
from gekko import GEKKO
import numpy as np

# Create the GEKKO model
m = GEKKO(remote=False)

# Define the variables
t = m.Var(value=20, name='t')  # Temperature in °C

# Define the fluid name for CoolProp
fluid_name = 'Water'

# Generate data for the cubic spline
n = 100  # Number of data points
T_vals = np.linspace(0, 100, n)  # Temperature range in °C
P_vals = [PropsSI('P', 'Q', 1, 'T', T + 273.15, fluid_name) / 1000 for T in T_vals]  # Saturation pressure in kPa

# Build the cubic spline in GEKKO
P_spline = m.Var(value=P_vals[0])
m.cspline(t, P_spline, T_vals, P_vals)

# Define the equations using the spline
m.Equation(t==P_spline)

# Solve the GEKKO model
m.solve()

# Print the results
for i in m._variables:
    print(i.name, i.value)

# Verify the calculations
print(f'GEKKO result: a + P_spline = {a.value[0] + P_spline.value[0]} (should be close to 0)')
print(f'GEKKO result: a + t = {a.value[0] + t.value[0]} (should be 0)')
```
