### ISSUE TITLE
m.GUI() server not found

### ISSUE THREAD

**Issue by nwoodbury** [BYU-PRISM/GEKKO#19]
Running Python 3 in a Windows 10 environment. When calling m.GUI(), a server is created, but when navigating to the page specified by the port, a 404 (page not found) error is returned.

**Comment by loganbeal** [comment]
@dhill2522 The Vue "static" folder didn't make it into the pip package.

**Comment by dhill2522** [comment]
@loganbeal Somehow it is still not including the static files even with your latest commit (5b8dc47). I just tried it with `pip install gekko` in a fresh virtualenv. The first time it looked like it worked because the browser had cached the page, but on a hard refresh it doesn't.

**Comment by loganbeal** [comment]
@dhill2522 I think I fixed it in the latest commit and pip package

**Comment by dhill2522** [comment]
Thanks! It works great now as far as I can tell.

**Comment by dhill2522** [comment]
@nwoodbury If you are interested in trying this again a `pip install --upgrade gekko` should do the trick now.
