### ISSUE TITLE
Discrete State Space Model Object Support

### ISSUE THREAD

**Issue by luxirp** [BYU-PRISM/GEKKO#190]
Hi,
I am writing this issue regarding the possibility of obtaining the state space model from the system equations like in Matlab (system identification toolbox). I have seen that the option of define the models using the matrix A, B, C and D is possible as indicated here (https://apmonitor.com/wiki/index.php/Apps/LinearStateSpace), however I would like to obtain the Matrix from the system equations or data. We have investigated that in this post (https://github.com/BYU-PRISM/GEKKO/issues/23) and it seems that in this commit a SS.py was created (https://github.com/BYU-PRISM/GEKKO/commit/93a5b8d7a3084492a0d03039f058552d61846641#diff-d89ae31a3c14a2e185f1ab2f6f800a90bf2fdce96197e58a404e4658188dcd47), however it is no longer available.
In case there is any function available to extract them within gekko, could you share?
Thank you,
Kind regards,
Lucia.

**Comment by APMonitor** [comment]
Identification of time series models is done with the `sysid()` function to produce an ARX model. See [12 Time Series](https://apmonitor.com/pds/notebooks/12_time_series.html) for examples on working with time-series models. There are exact transformations between model forms as shown here with exact simulation in each form:

```python
import numpy as np
from scipy import signal

# problem 1
A = [-4.0]
B = [2.0]
C = [1.0]
D = [0.0]
sys1 = signal.StateSpace(A,B,C,D)
t1,y1 = signal.step(sys1)

# problem 2
A = [[-3.0,0.0],[-2.0,-3.0]]
print(np.linalg.eig(A)[0])
B = [[4.0],[0.0]]
C = [0.5,0.5]
D = [0.0]
sys2 = signal.StateSpace(A,B,C,D)
t2,y2 = signal.step(sys2)

# problem 3
A = [[0.0,1.0],[-0.25,-0.5]]
print(np.linalg.eig(A)[0])
B = [[0.0],[0.75]]
C = [1.0,0.0]
D = [0.0]
sys3 = signal.StateSpace(A,B,C,D)
t = np.linspace(0,30,100)
u = np.zeros(len(t))
u[5:50] = 1.0 # first step input
u[50:] = 2.0  # second step input
t3,y3,x3 = signal.lsim(sys3,u,t)

# problem 4
A = [[-2.0,-6.0],[-8.0,8.0]]
print(np.linalg.eig(A)[0])
B = [[8.0],[0.0]]
C = [[0.0,1.0],[1.0,0.0]]
D = [[0.0],[0.0]]
sys4 = signal.StateSpace(A,B,C,D)
t4,y4 = signal.step(sys4)

import matplotlib.pyplot as plt
plt.figure(1)
plt.subplot(4,1,1)
plt.plot(t1,y1,'r-',linewidth=3)
plt.ylabel('Problem 1')
plt.legend(['y'],loc='best')
plt.subplot(4,1,2)
plt.plot(t2,y2,'b--',linewidth=3)
plt.ylabel('Problem 2')
plt.legend(['y'],loc='best')
plt.subplot(4,1,3)
plt.plot(t3,y3,'k-',linewidth=3)
plt.plot(t,u,'r-')
plt.ylabel('Problem 3')
plt.legend(['y','u'],loc='best')
plt.subplot(4,1,4)
plt.plot(t4,y4[:,0]+2.0,'r--',linewidth=3)
plt.plot(t4,y4[:,1]+2.0,'b-',linewidth=3)
plt.legend(['y1','y2'],loc='best')
plt.ylabel('Problem 4')
plt.xlabel('Time')
plt.show()
```

Subspace identification in state space form can offer some advantages, however, versus identifying separate ARX models between inputs and each output. There are ARX, Subspace, NN, and TF identification options with our open-source add-on to Seeq SysID. There is a way to run the Jupyter Notebook independently of Seeq as well.

https://seeq.readthedocs.io/en/stable/pages/introduction.html
