### ISSUE TITLE
Solver freezing

### ISSUE THREAD

**Issue by CSimsRun** [BYU-PRISM/GEKKO#22]
The solver is freezing when both disp and remote are false. The True/False, False/True, and True/True all work fine.

![image](https://user-images.githubusercontent.com/36426353/37420054-7e14f13a-277b-11e8-8e58-e8afc4671b05.png)

**Comment by loganbeal** [comment]
@CSimsRun @APMonitor This was a bug that only affected Windows. I fixed it in commit 1b7ff5344056c8c9aba5aa22d7df565ed93d41ab and included it in pip release 0.0.4b1.

Please confirm that this works for you.
