### ISSUE TITLE
Discrete State Space Model Object Support

### ISSUE THREAD

**Issue by APMonitor** [BYU-PRISM/GEKKO#23]
I'd like to request object support for state space models, especially discrete state space. These are supported in APM MATLAB and APM Python. 
https://github.com/APMonitor/apm_python/blob/master/example_lti_regression/
https://github.com/APMonitor/apm_matlab/tree/master/example_lti

Here is an example model: http://apmonitor.com/wiki/index.php/Apps/LinearStateSpace

The discrete state space model should be able to link with other models. If a discrete state space model is used, a uniform time discretization should be enforced or a warning issued if there are non-uniform time intervals.

There is also the apm_id function in APM MATLAB and APM Python that identifies Linear Time-Invariant (LTI) models from data and writes the APM model. Identification can be a separate / future effort. This request is to add support for state space models.

**Comment by loganbeal** [comment]
@APMonitor, I previously created a [GEKKO module](https://github.com/BYU-PRISM/GEKKO/blob/master/gekko/SS.py) for building state space models, but it doesn't use the APM lti object. The function accepts matrices A,B,C,[D], builds appropriately-sized python lists of MVs for the inputs (u), SVs for the states (x), and CVs for the outputs (y), and returns the python arrays u,x,y. 

Does this seem like appropriate default behavior for a GEKKO state space object? I can adapt this function to use the lti object instead (and enable the continuous/discrete time option) and connect the x,y, and u arrays through connections automatically. Further connections between models could either use x/y/u elements, or use GEKKO Connections to connect elements of x/y/u to variables of other models.

What are the attributes of the lti model to connect to? lit_instance.x[1:n], lit_instance.u[1:m] and lit_instance.y[1:p]?

**Comment by APMonitor** [comment]
Yes, those are the attributes to connect. I don't think the discrete state space model will work as a pure GEKKO implementation because there are special ways that it treats the model to implement the time series that likely wouldn't be possible with the GEKKO/APM model. I had to write an object so that it would do the connections to the other variables, especially when a discrete model is mixed with other continuous differential equations.

**Comment by loganbeal** [comment]
I modified state space support to use the APM lti object rather than build the model as Equations in commit 93a5b8d7a3084492a0d03039f058552d61846641. I connected GEKKO MVs to lti_object.u[1:m], SVs to lti_object.x[1:n] and CVs to lti_object.y[1:p], then returned these lists of MVs, SVs and CVs for the user to access in the script. APM fails silently after loading the lti model files: 
```
 ----------------------------------------------------------------
 APMonitor, Version 0.8.1
 APMonitor Optimization Suite
 ----------------------------------------------------------------


 --------- APM Model Size ------------
 Each time step contains
   Objects      :            1
   Constants    :            0
   Variables    :            8
   Intermediates:            0
   Connections  :            8
   Equations    :            0
   Residuals    :            0


 LTI Model Statistics
 -------------------------------------
 Dense Matrices
 Continuous Form
 Matrix    Dimension    Non-zeros
   A                 4 x           4                 0
   B                 4 x           2                 0
   C                 2 x           4                 0
   D                 2 x           2                 0
   E                 4 x           4                 0
 -------------------------------------
```
Do you have any ideas why it might be failing?

**Comment by APMonitor** [comment]
The error is that there are no D and E matrices specified. I need to update the code to provide a warning for the error or let the user skip matrices D when it is zeros(p,m) and E when it is an identity matrix eye(n,n). Most state space models are just A, B, and C.

**Comment by APMonitor** [comment]
Fixed the issue with LTI objects in v0.8.2. Code was stopping when matrix D was not available. It now just sets D to be zero if not found. One other issue that will need to be addressed in GEKKO is that APM LTI object uses starting index = 1 instead of index = 0 for sparse array notation. It will show an error if a row or column is zero.

**Comment by loganbeal** [comment]
State space models using APM lti objects has been added as of release 0.0.4b2

**Comment by loganbeal** [comment]
@APMonitor It looks like the remote servers may not have the most recent executable that supports this feature.

**Comment by APMonitor** [comment]
I updated byu.apmonitor.com and xps.apmonitor.com with the new version about 2 weeks ago. Is there a new error?

**Comment by loganbeal** [comment]
byu.apmonitor.com is on version 0.8.1, which fails silently as discussed above. Your fix to not require D and E in version 0.8.2 fixes this and is available locally and on xps.apmonitor.com.
```
----------------------------------------------------------------
 APMonitor, Version 0.8.1
 APMonitor Optimization Suite
 ----------------------------------------------------------------
```

**Comment by APMonitor** [comment]
byu.apmonitor.com is now upgraded to latest 0.8.2.

**Comment by loganbeal** [comment]
@APMonitor byu.apmonitor.com is back on version 0.8.1
