### ISSUE TITLE
Error when requesting DIAGLEVEL

### ISSUE THREAD

**Issue by abe-mart** [BYU-PRISM/GEKKO#24]
Setting the option DIAGLEVEL to any value other than zero results in an error.  On remote solve, the solve stops after model building but before the solver is called.  On a local solve, this error is displayed:

```
Error: Exception: Access Violation
At line 7184 of file files.f90 (Unit 10 "apm_lbt.txt")
```

**Comment by abe-mart** [comment]
For example:

```
from gekko import GEKKO
m = GEKKO()
x = m.Var()
m.Obj(x**2)
m.options.IMODE = 3
m.options.DIAGLEVEL = 1
m.solve(remote=True)
```

**Comment by loganbeal** [comment]
@abe-mart @APMonitor I can confirm an error on remote solve, though my local Windows solve runs without error. 

The remote solve gets to here before failing: 
```
...
...
 Number of state variables:            360
 Number of total equations: -          320
 Number of slack variables: -            0
 ---------------------------------------
 Degrees of freedom       :             40
 
 **********************************************
 Dynamic Control with Interior Point Solver
 **********************************************
```

**Comment by loganbeal** [comment]
@APMonitor My local Linux executable prints this error before failing:
 ```
...
**********************************************
 Steady State Optimization with Interior Point Solver
 **********************************************
  
Error: forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
apmonitor          00000000007C45F4  for__signal_handl     Unknown  Unknown
libpthread-2.23.s  00007FA28BBF9390  Unknown               Unknown  Unknown
libipopt.so.1      00007FA28D59898F  ipopenoutputfile_     Unknown  Unknown
apmonitor          000000000072937C  Unknown               Unknown  Unknown
apmonitor          0000000000459AF2  Unknown               Unknown  Unknown
apmonitor          00000000007456CF  Unknown               Unknown  Unknown
apmonitor          000000000040539E  Unknown               Unknown  Unknown
libc-2.23.so       00007FA28B83E830  __libc_start_main     Unknown  Unknown
apmonitor          00000000004052A9  Unknown               Unknown  Unknown
```

**Comment by APMonitor** [comment]
The problem was with how IPOPT opens the IPOPT.out file and writes to it when the printlevel >= 1. The IPOPT documentation says that printlevel can be between 0 and 10.
    printlevel = diaglevel*2
    printlevel = MIN(MAX(printlevel,0),10)
    ierr = ipopenoutputfile(iproblem, 'ipopt.out', printlevel)
This works in Windows (g95 compiler, IPOPT 3.10.2) but apparently there is a problem with Linux (ifort, IPOPT 3.12.8). I'm not sure if it is the compiler, the version of IPOPT, or the OS. I just set the print level to zero for IPOPT to get rid of this bug for Linux.
    printlevel = 0  ! print level >=1 crashes Linux
    ierr = ipopenoutputfile(iproblem, 'ipopt.out', printlevel)
This unfortunately removes a feature of IPOPT to allow more detailed diagnostics of the solver but does fix the crash bug. Public servers (Linux) and Windows executable with GEKKO is updated with the fix.

**Comment by APMonitor** [comment]
The first problem that @abe-mart posted was a different bug that is also fixed. Please open another issue if this bug isn't resolved. The apm_lbt.txt file is generated as a post-processing step when diaglevel>=2. I'm now checking that there is sufficient problem structure for a Lower Block Triangular (LBT) decomposition. This section is now skipped when the problem isn't square (same number of variables as equations) and when the number of variables and equations is at minimum 2.
