### ISSUE TITLE
Extra overrides.dbs properties

### ISSUE THREAD

**Issue by APMonitor** [BYU-PRISM/GEKKO#26]
GEKKO is writting MV properties LB and UB that are not needed. The APM executable ignores them so this isn't a critical issue.

APM.CYCLECOUNT = 0
APM.PRED_HOR = 1.0
APM.PRED_TIME = 60.0
p1.LB = 1e-05
p1.UB = 1
p1.FSTATUS = 0
p1.LOWER = 1e-05
p1.STATUS = 1
p1.UPPER = 1
p1.DCOST = 0.01

You can find this in overrides.dbs. The above is just the relevant section that includes the MV properties.

**Comment by loganbeal** [comment]
I removed this with commit ba4786b86366906061af6c9dc0302c2870e2e61c. 
I had previously deprecated LB and UB and had them match LOWER and UPPER. This commit removed the deprecated options.
