### ISSUE TITLE
Can't create gekko object when server is down

### ISSUE THREAD

**Issue by hansenb44** [BYU-PRISM/GEKKO#29]
When the default server is down a gekko object can't be created, even if only using the local solve option.

Ex: 
from gekko import*
m = GEKKO()

m.solve(remote = False)

Doesn't work when the default server is down.
But when I add the name of a working server:

from gekko import*
m = GEKKO(server='server_name')

m.solve(remote = False)

Then it works.

**Comment by loganbeal** [comment]
Fixed with release 0.1
