### ISSUE TITLE
"Could not retrieve results.json from server" after a successful solution

### ISSUE THREAD

**Issue by nsgates** [BYU-PRISM/GEKKO#30]
After many successful solutions of a model predictive controller over succeeding horizons, there is an error accessing the results of a successful solution. The readout is reproduced below. The solve was done remotely, from a computer with a wireless internet connection. 

@loganbeal raised the possibility that this problem could be caused by the IP address of the computer changing during the optimization process. This is the second time I have seen an error like this. @APMonitor, does this seem like the most likely cause?

I have connected my computer to the internet with an ethernet cable, with the hope that this will reduce the frequency of this error. I am pre-pending my model name with a string generated from the time and date, which should prevent over-writing other models. Would it be possible to add a feature that could disable the use of the computer's IP address in the model tracking from the APM side?

```
EXIT: Optimal Solution Found.
 
 The solution was found.
 
 The final value of the objective function is   -3238.64169605372     
 
 ---------------------------------------------------
 Solver         :  IPOPT (v3.9)
 Solution time  :    13.2771999999968      sec
 Objective      :   -3238.64165515089     
 Successful solution
 ---------------------------------------------------
 
Could not retrieve results.json from server
```

**Comment by abe-mart** [comment]
I encountered this same issue running on a wireless connection.

**Comment by APMonitor** [comment]
Yes, it may be due to an IP address switch. This is a server script PHP issue and not an APM issue. We would just need to remove the IP address from the application name. I had the IP address in the application name because it helps create separate applications for each user and prevents server conflicts. Perhaps we could revert to a username when it is available?

**Comment by loganbeal** [comment]
Sending a username to the server seems like a violation of privacy to me. What if we used cookies instead? We can keep a separate cookie in each GEKKO model [cookie jar](https://docs.python.org/3/library/http.cookiejar.html) and send it in the http header without much difficulty. On the PHP side, if there's not a cookie, use the default (IP address) behavior. Else, access the folder associated with the cookie.

**Comment by ericman314** [comment]
I think a random server-generated identifier would work just fine. But using a cookie as the vehicle probably won't work: if the model is initiated in Python, and then a browser window is opened to view the results, there is no way for the browser to pick up the cookie. But you can easily simulate the behavior of a cookie by including the identifier in the URL. The default behavior should be that the identifier is reused over each `m.solve()` request. If a user needs to reuse a session across multiple executions, then the identifier should be made accessible as a read/write attribute such as `m.id`. The user can then set the attribute to reuse an existing session.

Public IP addresses do not always uniquely identify a user (for example, two or more people on the same local network) and can even change. A randomly generated ID is more private than an IP address as well, and gives the user control over whether or not to reuse a session, or start clean.

**Comment by APMonitor** [comment]
The support for local solve in Windows, Linux, and ARM (Raspberry Pi) is making this less of an issue but it is still an important topic. About 8 years ago we started developing a server version that would require username and password to access the applications. However, this made the user experience more complicated versus just downloading a script and running it. I like the idea of m.id. If the ID is sufficiently long or includes alpha and numeric values then there would be virtually no chance of overlap by the client generated ID.

**Comment by ericman314** [comment]
IDs should be generated on the server. In PHP you could use something like:

```php
bin2hex(random_bytes(16));  // 6bd98a0c258f2369266f30605a460a7a

base64_encode(random_bytes(16));  // R+2CL/su6GlRjmEOHuDaPA==
```

These generate cryptographically secure (unpredictable) psuedo random numbers. You can change the 16 to as high as you need to prevent collisions, or use shorter IDs and check for collisions with each new generated ID (but still long enough to be difficult to guess).

The ID then acts like the IP address for each request. If a user wants to reuse an old session, they simply supply the same ID the server returned the time before. If a user wants to start a new session, he does not supply an ID, and the server generates a new one. Then periodically you can clean up files from IDs that haven't been accessed for a while.

**Comment by APMonitor** [comment]
I think we can retire this issue. The public server is so busy now that I need to kill long-standing jobs occasionally just to keep the server from getting overloaded. For users that need persistent sessions over a long period of time, it is likely better to install the [Windows APM](https://apmonitor.com/wiki/index.php/Main/APMonitorServer) or [Linux APM](https://apmonitor.com/wiki/index.php/Main/APMonitorServerLinux) server or solve locally with `remote=False`.
