### ISSUE TITLE
Support for higher-dimensional splines

### ISSUE THREAD

**Issue by nsgates** [BYU-PRISM/GEKKO#31]
I'd like to request support for higher-dimensional splines. I've found the 1-D splines to be very useful, and haven't noticed significant slow-downs compared with fitting a function to the data. The advantage in accuracy over a function fit is very beneficial. 2-D splines would be very useful for a suite of optimization scenarios, including my current research. 3-D would also be quite useful, although it may begin to cause some slowdowns depending on the implementation.

With the current 1-D spline capability, it should be possible to implement 2-D splines by building a series of 1-D splines in one dimension and using those to build splines in another dimension. Since this would also include smooth, continuous 1st and 2nd derivatives, it may be easier to implement than bicubic interpolation.

**Comment by loganbeal** [comment]
@nsgates, can you supply a minimal working example of a higher-dimensional spline? 
@APMonitor, how much development do you want to see from the community before you implement this in the back-end?

**Comment by nsgates** [comment]
@loganbeal, in Python or GEKKO?

**Comment by loganbeal** [comment]
@nsgates Python or Fortran

**Comment by nsgates** [comment]
@APMonitor, here is a Python script I created that will take in 2-D data and use 1-D splines to interpolate in 2 dimensions. 

```
# Use 1-D splines to interpolate in 2-D

# Notes:
# Assumes a rectangular grid.
# For best results, ensure the data points have equivalent precision across both dimensions.
# Author: Nathaniel Gates

import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import CubicSpline

# Create data
x = np.arange(-5, 5, 0.5)
y = np.arange(-5, 5, 1.0)
X, Y = np.meshgrid(x, y)
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)

# Use the dimension with the most data points to build new splines.
xlen = len(x)
ylen = len(y)
if xlen >= ylen: # Finer resolution along x axis; build additional splines in the x direction
    use_x = True
else: # Finer resolution along y axis; build additional splines in the y direction
    use_x = False

# Initialize plotting
fig = plt.figure()
ax = fig.gca(projection='3d')    

# Build splines in y direction
ys = {}
for i in range(xlen):
    ys[i] = CubicSpline(y, Z[:,i])
    ax.plot(X[:,i], y, ys[i](y), color = 'C0')
ax.plot(X[:,i], y, ys[i](y), color = 'C0', label='Splines in y direction')

# Build splines in x direction
xs = {}
for i in range(ylen):
    xs[i] = CubicSpline(x, Z[i,:])
    ax.plot(x, Y[i,:], xs[i](x), color = 'C1')
ax.plot(x, Y[i,:], xs[i](x), color = 'C1', label='Splines in x direction')

# Build additional splines to interpolate to inner points. Use whichever spline has finer discretization.
# Generate additional points
npts = 30
np.random.seed(0)
xrand = np.random.rand(npts)*(x.max()-x.min())+x.min()
yrand = np.random.rand(npts)*(y.max()-y.min())+y.min()

# Build splines, evaluate and plot the points
nval = np.zeros(npts)
for i in range(npts):
    xp = xrand[i]
    yp = yrand[i]
    if use_x == True: # Use splines that run in the x direction
        zn = np.zeros_like(x)
        for j in range(xlen):
            zn[j] = ys[j](yp)
        ns = CubicSpline(x, zn)
        zp = ns(xp)
        nval[i] = zp
    else: # Use splines that run in the y direction
        zn = np.zeros_like(y)
        for j in range(ylen):
            zn[j] = xs[j](xp)
        ns = CubicSpline(y, zn)
        zp = ns(yp)
        nval[i] = zp
    ax.plot([xp], [yp], [zp], 'o', color = 'C3')
ax.plot([xp], [yp], [zp], 'o', color = 'C3', label='Interpolated points')

# Make legend, set axes labels
ax.legend()
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
ax.view_init(elev=20, azim=-35)

plt.show()
```

![2-d_cubic_splines](https://user-images.githubusercontent.com/18149944/38892605-f605fac0-4244-11e8-87d0-a574c61a50c1.png)

**Comment by loganbeal** [comment]
Initial support added in commit e385ff23b34a0544293eb50d9044ea7197974a8f. @nsgates can you test it?

**Comment by APMonitor** [comment]
APMonitor servers are upgraded to support bsplines.
