### ISSUE TITLE
Intermediates do not appear in the results file when solving in sequential simulation (mode 7).

### ISSUE THREAD

**Issue by ConnorMcMillan** [BYU-PRISM/GEKKO#38]
I am trying to compare differences and debug between two versions of a model I have written in gekko. When solving dynamically in simultaneous mode, I am able to investigate the results closely by comparing the values of the intermediates which are written to the results file. The values of the intermediates are written to the results file alongside the variables. 

However, when solving in sequential mode, only the values of the variables are written to the results file. I need to see the values of the intermediates in addition to the values of the variables for the purpose of debugging and comparing the two models--a feature which apparently is not currently available. 

Thank you!

**Comment by abe-mart** [comment]
@APMonitor is there any update on this issue (IMODE 7 returning intermediate values)?  This would be helpful for our solar thermal work.  If it's not possible, we can try to work around the problem by making all intermediates into variables.

**Comment by APMonitor** [comment]
Issue is now resolved by adding this feature to APMonitor. New program available on Windows and Linux and on the public servers.
