### ISSUE TITLE
Add example for Model Predictive Control

### ISSUE THREAD

**Issue by parolandi** [BYU-PRISM/GEKKO#42]
** Current **

There is no example on MPC on https://gekko.readthedocs.io/en/latest/examples.html

** Desired **

An example on MPC, as this is a likely differentiating capability of GEKKO w.r.t. other optimization toolkits.

**Comment by APMonitor** [comment]
There are MPC examples posted to https://apmonitor.com/wiki/index.php/Main/GekkoPythonOptimization and http://apmonitor.com/wiki/index.php/Main/Control and https://github.com/BYU-PRISM/GEKKO/tree/master/examples  Logan also gave a nice webinar with examples posted to https://github.com/loganbeal/CAST_GEKKO_webinar

We need to add additional examples or links to the page as well.

**Comment by parolandi** [comment]
Sounds good! Thanks for considering this enhancement request

**Comment by APMonitor** [comment]
Updated the examples page to include MHE, MPC, and links to many other examples. @loganbeal - could you verify that the documentation updates aren't overwritten by sphynx or another type of documentation creator? I edited the rst files directly.

https://github.com/BYU-PRISM/GEKKO/blob/master/docs/index.rst
and
https://github.com/BYU-PRISM/GEKKO/blob/master/docs/examples.rst
