### ISSUE TITLE
Access named variables and params

### ISSUE THREAD

**Issue by ericman314** [BYU-PRISM/GEKKO#52]
Say I have the following, where I want to reuse a model in multiple places. Other than using the gekko model's built-in `_variables` attribute, is there a "right" way to access the variable `x`?

```py
def getModel():
  m = GEKKO()
  m.Var(value=5, name='x')
  return m

m = getModel()
# How to access variable x?
```

Putting `x` in the global scope is not what I intend.

**Comment by abe-mart** [comment]
One way that I have done this before is pack the variables back into the
model object.

def getModel():
  m = GEKKO()
  m.x = m.Var(value=5, name='x')
  return m

m = getModel()
print(m.x)

**Comment by ericman314** [comment]
Nice and clean. Thank you.

**Comment by APMonitor** [comment]
I like your idea to create a dictionary of variables such as:

def getModel():
    m = GEKKO()
    vars = {}
    vars['x'] = m.Var()
    vars['y'] = m.Param()
    return vars
print(vars)

There is checking in the GEKKO code to avoid collisions with built-in variable names. This isn't a problem, especially if you don't give your variables or parameters a non-default name. Feel free to open the issue again if you'd like more development work on this.
