### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by abe-mart** [BYU-PRISM/GEKKO#58]
There has been a lot of exciting development recently on Gekko.  I would submit that the project is in need of a [changelog](https://keepachangelog.com/en/1.0.0/) of some variety so people can see what's new.

**Comment by APMonitor** [comment]
I have the APMonitor changelog here: http://apmonitor.com/wiki/index.php/Main/ProductRoadmap  I'll work on something for Github as well.

**Comment by APMonitor** [comment]
Changelog.md created at https://github.com/BYU-PRISM/GEKKO/blob/master/CHANGELOG.md
