### ISSUE TITLE
Upper bound Constant Bug

### ISSUE THREAD

**Issue by abe-mart** [BYU-PRISM/GEKKO#6]
Setting the upper bound of a variable equal to a Constant raises an error:

```
from gekko import GEKKO
m = GEKKO()
myConst = m.Const(1)
myVar = m.Var(ub=myConst)
m.build_model()
```

produces:

```
> 
>   File "C:/Users/oacom/Documents/Python Scripts/testGEKKO/testBug.py", line 11, in <module>
>     m.build_model()
> 
>   File "C:\Users\oacom\Anaconda3\lib\site-packages\gekko\gekko.py", line 515, in build_model
>     if parameter.UB != None:
> 
>   File "C:\Users\oacom\Anaconda3\lib\site-packages\gekko\gk_operators.py", line 25, in __len__
>     return len(self.value)
> 
>   File "C:\Users\oacom\Anaconda3\lib\site-packages\gekko\gk_operators.py", line 122, in __len__
>     return len(self.value)
> 
> TypeError: object of type 'int' has no len()
```

**Comment by loganbeal** [comment]
GEKKO constants are objects with attributes name and value. In this case, you want the value:

```
from gekko import GEKKO 
m = GEKKO() 
myConst = m.Const(1) 
myVar = m.Var(ub=myConst.value) 
m.build_model()
```

If you find this tedious, I point you to the documentation:
> There is no functional difference between using a GEKKO Constant, a python variable or a magic number in the Equations. However, the Constant can be provided a name to make the .apm model more clear

I'm going to change the label to enhancement. Maybe in a future release we can make this syntax simpler.

**Comment by abe-mart** [comment]
If that is the case, why does setting a lower bound equal to a constant work?

**Comment by loganbeal** [comment]
@abe-mart I have tried to make the GEKKO variables and parameters act like they are just the value array, but it is not super reliable. For example, sometimes you can plot (using matplotlib) plt.plot(m.time,x) and it works just fine. Sometimes it does not. The more reliable/consistent behavior comes by specifying x.value directly. You are likely experiencing a consequence of this behavior

**Comment by abe-mart** [comment]
The problem appears to have been resolved.  I'm not getting the error anymore.
