### ISSUE TITLE
update gekko documentation

### ISSUE THREAD

**Issue by sivarammurugan** [BYU-PRISM/GEKKO#62]
Currently ,gekko documentation includes examples on how to create the various objects (stream, mass, flash etc)  as defined in chemical.py . However, it would be better if following details or examples are included in the documentation 

1. how to solve a simple unit operation such as flash , or mixing using gekko ?
2. how the properties of chemicals are calculated ?
3. what are the underlying thermodynamic models of unit operations?

**Comment by APMonitor** [comment]
Documentation is continuously updated. Increased support for thermophysical properties and unit operations is not a priority at this time.
