### ISSUE TITLE
remote = False not working on Mac

### ISSUE THREAD

**Issue by dmccrea107** [BYU-PRISM/GEKKO#79]
```
Error: dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/9/libquadmath.0.dylib
  Referenced from: /Users/dawson/Documents/Repositories/GEKKO/gekko/bin/apm_mac
  Reason: image not found
```
I was trying to run on my mac remote = False and was receiving this error. I installed gfortran as it seemed like that may have been the problem but was still getting this error. gcc is installed but redirects to clang. Any suggestions?

**Comment by APMonitor** [comment]
Does this solution work? https://stackoverflow.com/questions/57207357/dyld-library-not-loaded-usr-local-gfortran-lib-libgfortran-3-dylib-reason-im

**Comment by APMonitor** [comment]
What is your MacOS version? You may need `gcc` in addition to `gfortran`.

**Comment by dmccrea107** [comment]
I am running macOS Mojave version 10.14.6

Yes! That helped solve the problem. MacOS defaults to clang and so I had to ```brew install gcc``` to get around it. Unfortunately I am now running into 
```Error: dyld: lazy symbol binding failed: Symbol not found: ___emutls_get_address
  Referenced from: /Users/dawson/Documents/Repositories/GEKKO/gekko/bin/apm_mac
  Expected in: /usr/lib/libSystem.B.dylib```

**Comment by APMonitor** [comment]
Try installing `gfortran` with brew as well: `brew install gfortran`

**Comment by marcosfelt** [comment]
The issue for me was having gcc 8 installed instead of gcc 9. Using `brew install gcc` worked for me.  This should install `gfortran` as well, though if you already have it installed you might need to run `rm /usr/local/bin/gfortran` and then `brew link gcc` so everything works correctly.

**Comment by APMonitor** [comment]
I probably just need to link any dependencies in the executable so there isn't a dependency on gfortran shared libraries. I'll try to link the .a (static) libraries on the next release. It will make the apm_mac executable larger but it will hopefully eliminate this extra step.

**Comment by APMonitor** [comment]
Added gcc 9+ dependency information to the [documentation](https://gekko.readthedocs.io/en/latest/model_methods.html?highlight=remote#remote).
