### ISSUE TITLE
Support for pandas dataframe columns

### ISSUE THREAD

**Issue by abe-mart** [BYU-PRISM/GEKKO#8]
It would be nice to be able to set values for parameters and variables using columns from a pandas dataframe.  This can be achieved presently using `m.x.value = df['x'].values`, so a type check from GEKKO should be able to resolve the issue.

**Comment by abe-mart** [comment]
Okay, I just pushed a commit that should allow variable and parameter values to be set using a pandas series or dataframe column.

**Comment by APMonitor** [comment]
This seems to be an issue again. Do you know if support for DataFrames was removed?

https://groups.google.com/forum/#!topic/apmonitor/Oz_0RDVOCf8

**Comment by APMonitor** [comment]
With 0.2rc4, all input functions convert to a np.array().
