### ISSUE TITLE
Discretization of the ODEs

### ISSUE THREAD

**Issue by fbook98** [BYU-PRISM/GEKKO#84]
Hello,

I use an IPOPT solver for an MPC to control a simulated motor, but I have a small difference between the calculated values ​​of the solver and the simulated values ​​of the motor, so there is a permanent control deviation. Therefore I would like to know how exactly the discretion of the ODEs works.

**Comment by APMonitor** [comment]
Try `m.options.NODES=3`. The default is `2` and sometimes doesn't have the required accuracy. Here is more information https://apmonitor.com/do/index.php/Main/OrthogonalCollocation
