### ISSUE TITLE
feature request: Adaptive step-sizes in IMODE 7 solver

### ISSUE THREAD

**Issue by ben1post** [BYU-PRISM/GEKKO#88]
Thank you very much for the amazing work with Gekko!

I am using Gekko as a backend to solve marine ecosystem models and would like to have a more fail-proof way to sequentially solve models (without model optimization). 

As discussed in my [stackoverflow question](https://stackoverflow.com/questions/62588609/what-is-the-most-appropriate-solving-method-for-ode-or-pde-based-ecosystem-model/62598573#62598573), an adaptive step-size solver like scipy's odeint seems to be the more appropriate to test more complex ecosystem model structures without having to run grid indepenency tests with smaller time-steps.

Unfortunately my technical knowledge in the domain is not enough to judge the feasibility of different approaches to solve this. To me it would be just as useful, if there was a way to pass the Gekko model instance to odeint, or if there was a solver included with Gekko that can solve a Gekko model with adaptive time steps.

Could such a feature be added?

**Comment by ben1post** [comment]
I am currently working towards a first published version of my package and would be very interested in providing an interface to an adaptive step-size solver through GEKKO. Is there any chance this enhancement might be developed in the next few months? 

I would be very happy to help in the development, if I can. Would you already know specific steps or goals to work towards? Thank you!

**Comment by APMonitor** [comment]
Adaptive step sizes are now part of Gekko with `IMODE=7`. Please let us know if there are any additional issues.
